server:
  port: 8086

spring:
  application:
    name: fabo-finance-crm-service
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
