server:
  port: 8081

spring:
  application:
    name: fabo-auth-hrm-service
  profiles:
    active: dev
    group:
      product:
        - prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
