server:
  port: 8084

spring:
  application:
    name: fabo-payment-service
  profiles:
    active: dev
    group:
      product:
        - prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  vietqr:
    guid: A000000727
    country-code: VN
    currency-code: "704"
