server:
  port: 8080

spring:
  application:
    name: fabo-gateway
  profiles:
    active: dev
    group:
      product:
        - prod
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
